name: Sync Fork

on:
  schedule:
    - cron: '*/1 * * * *'  
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the target repository
      uses: actions/checkout@v2
      with:
        repository: Mohmed-saleh1/Consultaions-Platform
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        fetch-depth: 0

    - name: Add fork repository as remote
      run: |
        git remote add fork https://github.com/consultation-platform/Consultaions-Platform-Backend.git
        git fetch origin
        git push fork +refs/remotes/origin/*:refs/heads/* --force
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
